### ISSUE TITLE
Mesh custom resource can't be deleted if not owned

### ISSUE THREAD

**Issue by nckturner** [aws/aws-app-mesh-controller-for-k8s#101]
When using a mesh that isn't owned by the controller (we only create the mesh if it doens't already exist) the controller then assumes it owns the mesh, and we cannot delete the mesh object unless we can delete everything inside the mesh.

We should allow the mesh to be used by the controller, but not owned.  This means the controller should not try to delete the mesh when the mesh custom resource is deleted.  

I propose adding:
```
apiVersion: appmesh.k8s.aws/v1beta1
kind: Mesh
metadata:
  name: my-mesh
spec:
  ownership: shared
```
