### ISSUE TITLE
ColorApp Question: What's the purpose of the colorgateway VirtualService

### ISSUE THREAD

**Issue by eeeschwartz** [aws/aws-app-mesh-controller-for-k8s#113]
As a new App Mesh user, I spend a lot of time poring over the ColorApp example. I'm struggling to understand the purpose of the [colorgateway VirtualService](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/examples/color.yaml#L125).

It seems that VirtualService routes are only relevant for communication between VirtualNodes within a mesh. Correct so far?

In this case, why define a VirtualService for the colorgateway since it only receives traffic from outside of the mesh. At least that's how it's described in the [EKS walkthrough in the aws-app-mesh-examples repo](https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/eks/base.md#the-application). The curler pod makes requests to the colorgateway from outside of the mesh (i.e. it's deployed without an exposed port so no sidecar; also doesn't define a VirtualNode).

When you `kubectl exec curler-dc65c8c79-zbtkb -- curl colorgateway:9080/color`, the VirtualService config does not have an effect. For instance, I changed it to route traffic to `some-other-virtual-node` but it had no effect: 

```
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualService
metadata:
  name: colorgateway.appmesh-demo
  namespace: appmesh-demo
spec:
  meshName: color-mesh
  virtualRouter:
    listeners:
      - portMapping:
          port: 9080
          protocol: http
  routes:
    - name: gateway-route
      http:
        match:
          prefix: /color
        action:
          weightedTargets:
            - virtualNodeName: some-other-virtual-node
              weight: 1
```

`kubectl exec curler-dc65c8c79-zbtkb -- curl colorgateway:9080/color` still routed to the `colorgateway` service as before.

Please let me know what I'm missing. Thanks in advance.
