### ISSUE TITLE
Allow modification of AWS Cloud Map DNS record TTL

### ISSUE THREAD

**Issue by quentinplessis** [aws/aws-app-mesh-controller-for-k8s#127]
When creating a virtual node with Cloud Map as the service discovery mechanism, the TTL of the DNS record registered [seems to be currently fixed to `300` seconds](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/1ea35cb834a0f42b43b53788b3b85d86f27c785f/pkg/aws/cloudmap.go#L86).

It would be quite useful to be able to change that value, either by giving to app-mesh-controller a unique value for all virtual nodes, or better by being able to specify it in the `VirtualNode` resource. 

```yaml
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: my-node
spec:
  meshName: my-mesh
  serviceDiscovery:
    cloudMap:
      namespaceName: my-namespace.local
      serviceName: my-service
      ttl: 10
```

To my understanding using Cloud Map is necessary when spanning App Mesh across several clusters. When deleting a pod, the pod IP address is deregistered from Cloud Map in a few seconds/dozen of seconds but requests keep being redirected to the now-nonexisting-pod's IP address for 5 minutes due to the TTL.
