### ISSUE TITLE
Cloud Map instances health UNKNOWN during service discovery

### ISSUE THREAD

**Issue by rohithcj** [aws/aws-app-mesh-controller-for-k8s#132]
When using Cloud Map service discovery in app mesh controller, instances are getting registered as with health "UNKNOWN" even if health check is configured in Virtual Node listeners:

Virtual node configuration:

```
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: nodejs-app
  namespace: appmesh-workshop-ns
spec:
  meshName: appmesh-workshop
  listeners:
    - portMapping:
        port: 3000
        protocol: "http"
      healthCheck:
        healthyThreshold: 3
        intervalMillis: 10000
        path: "/"
        port: 3000
        protocol: http
        timeoutMillis: 5000
        unhealthyThreshold: 3

  serviceDiscovery:
    cloudMap:
      namespaceName: appmeshworkshop.pvt.local
      serviceName: nodejs
```

Health Status in Cloud Map:
```
$ aws servicediscovery discover-instances --namespace appmeshworkshop.pvt.local --service-name nodejs| jq '.Instances[].HealthStatus'
"UNKNOWN"
"UNKNOWN"
"UNKNOWN"
```
