### ISSUE TITLE
Controller can't reconcile between spec and API response when default values are set

### ISSUE THREAD

**Issue by efe-selcuk** [aws/aws-app-mesh-controller-for-k8s#133]
### Summary

Some fields like listener health checks include defaults that are set by the controller. The state of the resource with defaults isn't stored, and the current diff'ing logic does deep equality checks between the spec stored in the controller and the API response. These two values are never equal, so the controller continuously calls update with the desired spec.

This affects any case where the API response doesn't match the CRD spec.

### Steps to Reproduce

Create a simple virtual node with health checks:

```
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
  name: bugmesh
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: Mesh
metadata:
  name: bugmesh
  namespace: bugmesh
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: healthcheck
  namespace: bugmesh
spec:
  meshName: bugmesh
  listeners:
    - portMapping:
        port: 8080
        protocol: http
      healthCheck:
        path: "/health"
  serviceDiscovery:
    dns:
      hostName: front.local
```

Describe the virtual node, see the defaults:

```
{
    "virtualNode": {
...
                {
                    "healthCheck": {
                        "healthyThreshold": 10,
                        "intervalMillis": 30000,
                        "path": "/health",
                        "port": 8080,
                        "protocol": "http",
                        "timeoutMillis": 5000,
                        "unhealthyThreshold": 2
                    },
...
    }
}
```

Observe controller logs:

```
I0304 23:56:25.334839       1 virtualnode.go:99] Created virtual node healthcheck-bugmesh
I0304 23:56:25.381103       1 virtualnode.go:108] Updated virtual node healthcheck-bugmesh
I0304 23:56:55.338309       1 virtualnode.go:108] Updated virtual node healthcheck-bugmesh
I0304 23:57:25.357843       1 virtualnode.go:108] Updated virtual node healthcheck-bugmesh
```

### Workaround

I believe the workaround to prevent this would be to specify a spec that is identical to the one that the API would produce.

### Additional Context

[Listener health checks](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/aws/appmesh.go#L342) is an example of where we set defaults. I believe [the value here](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/controller/virtualnode.go#L35) is simply the deserialized VirtualNode from the yaml, without defaults. [vnodeNeedsUpdate](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/controller/virtualnode.go#L206) does a straightforward deep comparison, and will see that the response from the API doesn't match.

For something like CloudMap service discovery, we mutate the spec before comparing: https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/controller/virtualnode.go#L487

### Options for a Fix

This is specific to the virtual node handling, I haven't checked in other resources. I don't know if all of these are viable.

1. In [mutateVirtualNodeForProcessing](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/controller/virtualnode.go#L487), replicate the defaulting logic to set the defaults. Or potentially set the defaults exclusively here?
1. In [vnodeNeedsUpdate](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/controller/virtualnode.go#L250), instead of using the reflect library, do manual checking and ignore a diff when some fields are not set in the desired spec.
1. ~~In [handleVNode](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/controller/virtualnode.go#L96-L105), overwrite the internal spec with the result of the create/update call, which will reflect the "real" spec.~~ Likely not viable since external systems may be attempting to reconcile against the spec, e.g. gitops.
