### ISSUE TITLE
Controller can't reconcile if multiple backends with same name exist

### ISSUE THREAD

**Issue by efe-selcuk** [aws/aws-app-mesh-controller-for-k8s#135]
### Summary 

Similar to #133 

If a virtual node spec has multiple backends with the same name, the create API will accept them (see aws/aws-app-mesh-roadmap#170 for bug report), but the controller moves along. The describe call will return a single backend, so the controller never reconciles with the CRD spec.

I believe this is an invalid/ambiguous use case in the current API, so the API should return a client error, but in the meantime, we can patch this in the controller, and also handle the "repeated updates" bug like in #133.

This was not particularly problematic up until now because the struct _only_ contained the virtual service name. But now that we have backend client policies (#130), they're more distinguishable (and cause some additional calls to ACM on each update attempt).

### Steps to reproduce

Create a virtual node with two identical backends

```
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
  name: meshy
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: Mesh
metadata:
  namespace: meshy
  name: doublebackends
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: doublebackends
  namespace: meshy
spec:
  meshName: doublebackends
  backends:
    - virtualService:
        virtualServiceName: some.cool.svc
    - virtualService:
        virtualServiceName: some.cool.svc
```

Describe and see that it only has one backed from the API

```
mactop % appmesh describe-virtual-node --mesh-name doublebackends --virtual-node-name doublebackends-meshy
{
    "virtualNode": {
        "meshName": "doublebackends",
...
        "spec": {
            "backends": [
                {
                    "virtualService": {
                        "virtualServiceName": "some.cool.svc"
                    }
                }
            ]
        },
        "status": {
            "status": "ACTIVE"
        },
        "virtualNodeName": "doublebackends-meshy"
    }
}
```

If you inspect the controller logs you'll also see repeated `Updated virtual node` logs.
