### ISSUE TITLE
AppMesh naming conventions

### ISSUE THREAD

**Issue by stefanprodan** [aws/aws-app-mesh-controller-for-k8s#14]
The virtual nodes and virtual services could be referenced using Kubernetes naming `name.namespace`. 

Assuming the webhook injects the virtual node name as `controllerName-namespace`, a virtual service for A/B testing across namespaces would look like:

```yaml
apiVersion: appmesh.k8s.aws/v1alpha1
kind: VirtualService
metadata:
  name: frontend # appmesh name: frontend.prod.svc.cluster.local
  namespace: prod
spec:
  meshName: global.appmesh-system
  virtualRouter:
    name: frontend-router
  routes:
    - name: frontend-route
      http:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeName: frontend.prod # appmesh name: frontend-prod
              weight: 50
            - virtualNodeName: frontend.test # appmesh name: frontend-test
              weight: 50
---
apiVersion: appmesh.k8s.aws/v1alpha1
kind: VirtualNode
metadata:
  name: frontend # appmesh name: frontend-test
  namespace: test
spec:
  meshName: global.appmesh-system
  listeners:
    - portMapping:
        port: 9898
        protocol: http
  serviceDiscovery:
    dns:
      hostName: frontend.test.svc.cluster.local
```

The virtual service will resolve `frontend.prod` - `frontend.prod.svc.cluster.local`:

```yaml
apiVersion: appmesh.k8s.aws/v1alpha1
kind: VirtualNode
metadata:
  name: ingress
  namespace: appmesh-system
spec:
  meshName: global.appmesh-system
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: ingress.appmesh-system.svc.cluster.local
  backends:
    - virtualService:
        virtualServiceName: frontend.prod # appmesh name: frontend.prod.svc.cluster.local
```
