### ISSUE TITLE
application health check failed when added envoy side car in pod

### ISSUE THREAD

**Issue by samrui** [aws/aws-app-mesh-controller-for-k8s#147]
**Summary**
application health check failed when I added side car in the pod.

**Steps to Reproduce**
I just deployed a java web appliacation.
When namespace doesn't label "appmesh.k8s.aws/sidecarInjectorWebhook=enabled", it works well.
One pod with one container, status is running.

```
[centos@ip-10-103-218-60 k8s]$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
app-a-deployment-69865b99c9-r4qwj      1/1     Running   0          2m5s
```
But when I label namespace with "appmesh.k8s.aws/sidecarInjectorWebhook=enabled" and restart the pod, envoy container can start successfully, but the application container can't start.
The related ELB has no healthy targets.

```
[centos@ip-10-103-218-60 k8s]$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
app-a-deployment-69865b99c9-k96np      1/2     Running   1          2m50s

```

Following is my k8s yaml.
```
apiVersion: v1
kind: Service
metadata:
  namespace: sam-demo
  name: app-a-service
  labels:
    k8s-app: app-a-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    k8s-app: app-a-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sam-demo
  name: app-a-deployment
  labels:
    k8s-app: app-a-deployment

spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: app-a-pod
  template:
    metadata:
      namespace: sam-demo
      name: app-a-pod
      labels:
        k8s-app: app-a-pod
    spec:
      containers:
        - name: app-a-container
          image: xxx.dkr.ecr.us-east-1.amazonaws.com/app-a:1.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3

```
