### ISSUE TITLE
Docs are Inconsistent for VirtualNode backends array

### ISSUE THREAD

**Issue by kferrone** [aws/aws-app-mesh-controller-for-k8s#175]
So I am new to AppMesh. I have our apps working with AppMesh and so far so good. I simply added the CRD kinds in our Helm charts. However I did run into some issues with the backend services. 

I am also having trouble finding some more detailed examples of using the CRDs in k8s. I read through the CRDs and it seems inconsistent with [the docs I read here](https://docs.aws.amazon.com/app-mesh/latest/userguide/mesh-k8s-integration.html) and the [docs here](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/docs/design.md).  I also can't find any examples of using Appmesh CRDs in the official examples repo either, [aws/aws-app-mesh-examples](https://github.com/aws/aws-app-mesh-examples), it is always using cloudformation. 

The main issue is the docs say there is a backend section like below for `VirtualNodes`:
```yaml
backends:
  - virtualService:
       virtualServiceName: my-service-b.my-app-1.svc.cluster.local
```
However in the VirtualNode CRD, I can't find any mention of `virtualService` or `virtualServiceName` and it's definitely not in the backends array. I do see a definition for backends array like below:
```yaml
oneOf:
- type: object
   properties:
     backendService:
       type: object
       properties:
         clientPolicy:
           type: object
           properties: ...
         name:
           type: string  
```
which suggests the examples and docs should be like below:
```yaml
backends:
  - backendService:
       name: my-service-b.my-app-1.svc.cluster.local
```
Am I correct? Should I trust the docs or the CRD?
