### ISSUE TITLE
Virtual node health check for EKS

### ISSUE THREAD

**Issue by khacminh** [aws/aws-app-mesh-controller-for-k8s#188]
Hi,

Does App Mesh for EKS support health check? I create a virtual node from the following manifest file

```yaml
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: echo
  namespace: my-namespace
spec:
  meshName: test-mesh
  listeners:
    - portMapping:
        port: 3000
        protocol: http
      healthCheck:
        healthyThreshold: 2
        intervalMillis: 5000
        path: "/healthcheck"
        port: 3000
        protocol: "http"
        timeoutMillis: 2000
        unhealthyThreshold: 2
  serviceDiscovery:
    dns:
      hostName: echo.my-namespace.svc.cluster.local
```

However, on my App Mesh console, the health check is not added. When checking the appmesh-controller log, I see that it keeps updating the virtual node every 30s.

<img width="1062" alt="Screen Shot 2020-05-02 at 18 50 42" src="https://user-images.githubusercontent.com/13713865/80863345-d6d50a80-8ca5-11ea-9e1b-2c807a92ae13.png">
