### ISSUE TITLE
Proposal: Add injector CRD

### ISSUE THREAD

**Issue by stefanprodan** [aws/aws-app-mesh-controller-for-k8s#34]
The [injector](https://github.com/aws/aws-app-mesh-inject) configuration could be done dynamically via a Kubernetes custom resource. This would allow different configurations without installing the webhook in each namespace.

Example:

```yaml
apiVersion: appmesh.k8s.aws/v1beta1
kind: Injector
metadata:
  name: envoy-x-ray
  namespace: prod
spec:
  meshName: my-mesh
  routing:
    version: "v1.0.0" # iptables init container tag
    ignoredIPs: "169.254.169.254"
  proxying:
    version: "v1.9.0.0-prod" # Envoy sidecar container tag
    logLevel: info
    egress:
      - "*.amazonaws.com" # external 
      - "*.my-namespace.svc.cluster.local" # internal
  tracing:
    enabled: true
    version: "v1.0.0" # X-Ray sidecar container tag
    traceSampling: 0.20 # percentage of trace sampling range (0.00 - 100.00)
```
