### ISSUE TITLE
Appmesh Controller crashloop when update existing VirtualNode with existing serviceName in cloudmap from another virtualnode in another mesh

### ISSUE THREAD

**Issue by caleygoff-invitae** [aws/aws-app-mesh-controller-for-k8s#397]
**Describe the bug**
This bug is similar to the serviceDiscovery PR where appmesh would lose track of existing objects, which was resolved in https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/362.  And while the symptoms are related to serviceDiscovery this seems to show up when updating an existing VirtualNode, or even creating a new VirtualNode using an existing serviceName that exists in a cloudMap Namespace from another VirtualNode in another cluster using the same serviceName that might exist in a different mesh. 

In other words the controller ends up in a CrashLoopBackOff if a VirtualNode is attempting to use a serviceName that exists already in a "shared" cloudMap, that another cluster(VirtualNode) is also using

**Steps to reproduce**
Create a Cloudmap `some-internal.corp-cloud.com`
Standup VirtualNode and VirtualService and Mesh1 in Cluster1
Stand up VirtualNode and VirtualService and Mesh2 in Cluster2
In cluster2 while the apply tries to happen the error can be observed in the appmesh-controller logs, and should print something to shell if using kubectl on the second cluster.

The VirtualNode `front` are using the same cloudmap backend `some-internal.corp-cloud.com` and happened to be using attempting to use the same serviceName `front`, and each were using their own mesh. I ended up with a stack trace that can be found below the yaml samples

Cluster 1 Using its own mesh with awsCloudMap.namespaceName `some-internal.corp-cloud.com` with a awsCloudMap.serviceName `front` 

```
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
    mesh: mesh1
  name: appmesh-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: ""
  name: mesh-serviceaccount
  namespace: appmesh-test
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: mesh1
spec:
  namespaceSelector:
    matchLabels:
      mesh: mesh1
---
apiVersion: v1
kind: Service
metadata:
  name: colorapp
  namespace: appmesh-test
spec:
  ports:
  - port: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: appmesh-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: front
  type: ClusterIP
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: front
  namespace: appmesh-test
spec:
  backendDefaults:
    clientPolicy:
      tls:
        enforce: true
        validation:
          trust:
            acm:
              certificateAuthorityARNs:
              - arn:aws:acm-pca:us-east-1:<redacted>:certificate-authority/ffead368-34ee-11eb-b894-2f1668427829
  backends:
  - virtualService:
      virtualServiceARN: arn:aws:appmesh:us-east-1:<redacted>:mesh/mesh1/virtualService/colorapp.appmesh-test.svc.cluster.local
  listeners:
  - portMapping:
      port: 8080
      protocol: http
  podSelector:
    matchLabels:
      app: front
  serviceDiscovery:
    awsCloudMap:
      namespaceName: some-internal.corp-cloud.com
      serviceName: front
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: front-router
  namespace: appmesh-test
spec:
  listeners:
  - portMapping:
      port: 8080
      protocol: http
  routes:
  - httpRoute:
      action:
        weightedTargets:
        - virtualNodeRef:
            name: front
          weight: 1
      match:
        prefix: /color
    name: color-route
---
```

Cluster 2 Using different mesh using the same awsCloudMap.namespaceName `some-internal.corp-cloud.com` with the same awsCloudMap.serviceName `front`
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    mesh: test-mesh
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: test-mesh
spec:
  namespaceSelector:
    matchLabels:
      mesh: test-mesh
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-meshuser
  namespace: test
  annotations:
    eks.amazonaws.com/role-arn: ""
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: front
  namespace: test
spec:
  podSelector:
    matchLabels:
      app: front1
  listeners:
    - portMapping:
        port: 8080
        protocol: http
      healthCheck:
        protocol: http
        path: '/ping'
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 5000
  backends:
    - virtualService:
        virtualServiceRef:
          name: color
  backendDefaults:
    clientPolicy:
      tls:
        enforce: true
        validation:
          trust:
            acm:
              certificateAuthorityARNs:
                - arn:aws:acm-pca:us-east-1:<redacted>:certificate-authority/ffead368-34ee-11eb-b894-2f1668427829
  serviceDiscovery:
    awsCloudMap:
      namespaceName: some-internal.corp-cloud.com
      serviceName: front
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: color
  namespace: test
spec:
  awsName: color.test.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: color
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: test
  name: color
spec:
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  routes:
    - name: color-route-blue
      priority: 10
      httpRoute:
        match:
          prefix: /
          headers:
            - name: color_header
              match:
                exact: blue
        action:
          weightedTargets:
            - virtualNodeRef:
                name: blue
              weight: 1
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: blue
  namespace: test
spec:
  podSelector:
    matchLabels:
      app: color
      version: blue
  listeners:
    - portMapping:
        port: 8080
        protocol: http
      healthCheck:
        protocol: http
        path: '/ping'
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 5000
      tls:
        mode: STRICT
        certificate:
          acm:
            certificateARN: arn:aws:acm:us-east-1:<redacted>:certificate/9d71c916-34ef-11eb-8052-a791ed6d8311
  serviceDiscovery:
    awsCloudMap:
      attributes:
        - key: color
          value: blue
      namespaceName: some-internal.corp-cloud.com
      serviceName: color
---
apiVersion: v1
kind: Service
metadata:
  name: color-blue
  namespace: test
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: color
    version: blue
---
apiVersion: v1
kind: Service
metadata:
  name: color
  namespace: test
spec:
  ports:
    - port: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: test
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: front
    version: front
---
```

```
E1202 16:03:39.319067       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 409 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x178ee40, 0x29cb430)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/runtime/runtime.go:48 +0x82
panic(0x178ee40, 0x29cb430)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/aws/aws-app-mesh-controller-for-k8s/pkg/cloudmap.(*defaultResourceManager).updateCRDVirtualNode(0xc00002a080, 0x1d52f00, 0xc000136020, 0xc0002a4b60, 0xc000885d00, 0x5, 0xc000885d00)
	/workspace/pkg/cloudmap/resource_manager.go:462 +0x129
github.com/aws/aws-app-mesh-controller-for-k8s/pkg/cloudmap.(*defaultResourceManager).Reconcile(0xc00002a080, 0x1d52f00, 0xc000136020, 0xc0002a4b60, 0xc0002a4b60, 0xc00084b9b0)
	/workspace/pkg/cloudmap/resource_manager.go:110 +0x1b9
github.com/aws/aws-app-mesh-controller-for-k8s/controllers/appmesh.(*cloudMapReconciler).reconcileVirtualNodeWithCloudMap(0xc0008c4280, 0x1d52f00, 0xc000136020, 0xc0002a4b60, 0x13, 0xc000845d2c)
	/workspace/controllers/appmesh/cloudmap_controller.go:92 +0x110
github.com/aws/aws-app-mesh-controller-for-k8s/controllers/appmesh.(*cloudMapReconciler).reconcile(0xc0008c4280, 0xc0008ad800, 0x13, 0xc000845d2c, 0x3, 0x5fc7badb, 0xacbd418)
	/workspace/controllers/appmesh/cloudmap_controller.go:82 +0x151
github.com/aws/aws-app-mesh-controller-for-k8s/controllers/appmesh.(*cloudMapReconciler).Reconcile(0xc0008c4280, 0xc0008ad800, 0x13, 0xc000845d2c, 0x3, 0x0, 0x1, 0xc000360d00, 0x470bd8)
	/workspace/controllers/appmesh/cloudmap_controller.go:59 +0x57
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000936540, 0x17f78e0, 0xc0007aedc0, 0x1914500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000936540, 0x203000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000936540)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00084b900)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00084b900, 0x1d17340, 0xc0005645d0, 0xc000aaa001, 0xc0001161e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00084b900, 0x3b9aca00, 0x0, 0xc000043701, 0xc0001161e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133 +0xe2
k8s.io/apimachinery/pkg/util/wait.Until(0xc00084b900, 0x3b9aca00, 0xc0001161e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x305
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1590a49]
```

**Expected outcome**
At the very least I expected the appmesh-controller to swallow the error and tell me that the serviceName existed already and cannot be created, or updated. I had to rename the serviceName in cluster2, to `front1`.

I think I discovered, that at least it is not intended to share cloudmap namespaces, across different meshes -- this part true? 

**Environment**

* App Mesh controller version: appmesh-controller-1.2.0
* Envoy version: v1.15.1.0-prod
* Are you using any integrations? X-ray, Jaeger etc. If so versions? None
* Kubernetes version: 1.17
* Using EKS (yes/no), if so version? eks.5
