### ISSUE TITLE
Which component use a marked packet and mangle table?

### ISSUE THREAD

**Issue by ueokande** [aws/aws-app-mesh-controller-for-k8s#402]
We have an AppMesh cluster in the EKS with an [appmesh-controller](https://github.com/aws/aws-app-mesh-controller-for-k8s).  We investigated the network configured by AppMesh, but cannot understand how to use a marked packet and mangle table.

An init container (`aws-appmesh-proxy-route-manager:v3-prod`) injected by the controller initializes a pod's ingress network by the following:

```sh
APPMESH_LOCAL_ROUTE_TABLE_ID="100"                                                             
APPMESH_PACKET_MARK="0x1e7700ce"                                                               

# <snip>

iptables -t mangle -N APPMESH_INGRESS

# <snip>

ip rule add fwmark "$APPMESH_PACKET_MARK" lookup $APPMESH_LOCAL_ROUTE_TABLE_ID
ip route add local default dev lo table $APPMESH_LOCAL_ROUTE_TABLE_ID
```

We cannot find which component sets a mark `0x1e7700ce` to packets and which component uses a mangle table.  Istio sets a mark to packets in the mangle table [here](https://github.com/istio/cni/blob/master/tools/packaging/common/istio-iptables.sh#L393).  We confirm the mangle table in the AppMesh, but it's empty:

```console
$ iptables -t mangle -L 
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain APPMESH_INGRESS (0 references)
target     prot opt source               destination
```

Here the questions:

1. When and where a marked packet is used in App Mesh? (or not implemented yet?)
2. The mark and routing rule are formally specified in a document? Is it safe to use a mark `0x1e7700ce` by the user's service, or the spec can be changed in the future?

**Comment by cgchinmay** [comment]
@ueokande Hi, Could you list the steps to reproduce the iptables output that you saw or just explain where did you run the iptables command ? like which pod, container or host ?

**Comment by ueokande** [comment]
Here are the steps to reproduce it:

1. Create a namespace `my-apps` by following [getting started](https://docs.aws.amazon.com/app-mesh/latest/userguide/getting-started-kubernetes.html).
2.  Run `kubectl apply` with the following manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: my-apps
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: debug
        image: 840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:v3-prod
        command: ["tail"]
        args: ["-f", "/dev/null"]
        securityContext:
          capabilities:
            add:
            - NET_ADMIN

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: my-apps
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: my-service-a
  namespace: my-apps
spec:
  podSelector:
    matchLabels:
      app: nginx
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: nginx.my-apps.svc.cluster.local
```

3. Run iptables inside a `debug` container:
```console
$ kubectl -nmy-apps exec -cdebug nginx-xxxxxxxxxx-xxxxx -- iptables -t mangle -L
$ kubectl -nmy-apps exec -cdebug nginx-xxxxxxxxxx-xxxxx -- ip rule    # we can also see a fwmark rule

```
