### ISSUE TITLE
Feature request: Use custom image URI l for busybox when using Jaeger

### ISSUE THREAD

**Issue by hiraken-w** [aws/aws-app-mesh-controller-for-k8s#405]
**Is your feature request related to a problem?**

The busybox container image uses DockerHub.
[aws-app-mesh-controller-for-k8s/jaeger.go at v1.2.1 · aws/aws-app-mesh-controller-for-k8s](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/v1.2.1/pkg/inject/jaeger.go#L42)

Therefore, as a countermeasure to DockerHub pull limit, there are a use case that we want to change the container image URI.

**Describe the solution you'd like**

I would like to change the image URI in program arguments or ConfigMap.
Alternatively, you can just change the image URI to not use DockerHub, such as ECR Public Gallery.

**Describe alternatives you've considered**

I think that the workaround is to have the initContainer "inject-jaeger-config" in the manifest beforehand.
In this case, the mutation webhook inject does not make any changes.

```
      initContainers:
      - command:
        - sh
        - -c
        - |
          cat <> /tmp/envoy/envoyconf.yaml
          tracing:
           http:
            name: envoy.tracers.zipkin
            typed_config:
             "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
             collector_cluster: jaeger
             collector_endpoint: "/api/v2/spans"
             collector_endpoint_version: HTTP_JSON
             shared_span_context: false
          static_resources:
            clusters:
            - name: jaeger
              connect_timeout: 1s
              type: STRICT_DNS
              lb_policy: ROUND_ROBIN
              load_assignment:
                cluster_name: jaeger
                endpoints:
                - lb_endpoints:
                  - endpoint:
                     address:
                      socket_address:
                       address: appmesh-jaeger.appmesh-system
                       port_value: 9411
          EOF
               cat /tmp/envoy/envoyconf.yaml
        image: [custom image URI]
        name: inject-jaeger-config
        volumeMounts:
        - mountPath: /tmp/envoy
          name: envoy-tracing-config
      volumes:
      - emptyDir: {}
        name: envoy-tracing-config
```
