### ISSUE TITLE
Can't create virtual gateway envoy deployment in a eks envrionment, which is enable xray tracing.

### ISSUE THREAD

**Issue by eph6666** [aws/aws-app-mesh-controller-for-k8s#406]
**Describe the bug**
Can't create virtual gateway envoy deployment in a eks envrionment, which is enable xray tracing.
You can chime me for more details by **zacwang@**.

**Steps to reproduce**
1. Create a eks cluster.
2. Install appmesh controller
3. Deploy microservices, Virtualnode, Virtualrouter, Virtualservice
4. Deploy Virtualgateway. Everything is ok.
5. Enable xray tracing
6. Recreate Virtualgateway envoy. Pod create failed.
7.  will recover when xray is disabled

Replicaset have following Events:
```
  Type     Reason        Age                From                   Message
  ----     ------        ----               ----                   -------
  Warning  FailedCreate  100s               replicaset-controller  Error creating: Pod "vote-gw-748996dc-f2cfk" is invalid: spec.containers[1].ports[0].containerPort: Required value
  Warning  FailedCreate  100s               replicaset-controller  Error creating: Pod "vote-gw-748996dc-lh86w" is invalid: spec.containers[1].ports[0].containerPort: Required value
  Warning  FailedCreate  100s               replicaset-controller  Error creating: Pod "vote-gw-748996dc-r78mp" is invalid: spec.containers[1].ports[0].containerPort: Required value
  Warning  FailedCreate  100s               replicaset-controller  Error creating: Pod "vote-gw-748996dc-8csxm" is invalid: spec.containers[1].ports[0].containerPort: Required value
  Warning  FailedCreate  100s               replicaset-controller  Error creating: Pod "vote-gw-748996dc-829l8" is invalid: spec.containers[1].ports[0].containerPort: Required value
  Warning  FailedCreate  100s               replicaset-controller  Error creating: Pod "vote-gw-748996dc-drknd" is invalid: spec.containers[1].ports[0].containerPort: Required value
  Warning  FailedCreate  100s               replicaset-controller  Error creating: Pod "vote-gw-748996dc-n2ls9" is invalid: spec.containers[1].ports[0].containerPort: Required value
  Warning  FailedCreate  100s               replicaset-controller  Error creating: Pod "vote-gw-748996dc-w8zgz" is invalid: spec.containers[1].ports[0].containerPort: Required value
  Warning  FailedCreate  99s                replicaset-controller  Error creating: Pod "vote-gw-748996dc-slm9j" is invalid: spec.containers[1].ports[0].containerPort: Required value
  Warning  FailedCreate  18s (x6 over 98s)  replicaset-controller  (combined from similar events): Error creating: Pod "vote-gw-748996dc-cxvm8" is invalid: spec.containers[1].ports[0].containerPort: Required value
```

appmesh-controller have following debug-level log:
```
{"level":"debug","ts":1608198102.3334737,"logger":"mutating_handler","msg":"mutating webhook request","request":{"uid":"c251863d-2d37-4d2b-90c3-742ce868bc49","kind":{"group":"","version":"v1","kind":"Pod"},"resource":{"group":"","version":"v1","resource":"pods"},"requestKind":{"group":"","version":"v1","kind":"Pod"},"requestResource":{"group":"","version":"v1","resource":"pods"},"namespace":"vote","operation":"CREATE","userInfo":{"username":"system:serviceaccount:kube-system:replicaset-controller","uid":"d4310765-4fdc-4c5f-a10e-9c38de3ec6fd","groups":["system:serviceaccounts","system:serviceaccounts:kube-system","system:authenticated"]},"object":{"kind":"Pod","apiVersion":"v1","metadata":{"generateName":"vote-gw-79cdd46c96-","creationTimestamp":null,"labels":{"app":"vote-gw","pod-template-hash":"79cdd46c96","type":"gateway"},"annotations":{"kubernetes.io/psp":"eks.privileged"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaSet","name":"vote-gw-79cdd46c96","uid":"661541c5-4be6-4890-8bd4-20e9c4151247","controller":true,"blockOwnerDeletion":true}]},"spec":{"volumes":[{"name":"default-token-7wbgw","secret":{"secretName":"default-token-7wbgw"}}],"containers":[{"name":"envoy","image":"840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.15.1.0-prod","ports":[{"containerPort":8443,"protocol":"TCP"}],"env":[{"name":"ENABLE_ENVOY_XRAY_TRACING","value":"0"}],"resources":{},"volumeMounts":[{"name":"default-token-7wbgw","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"default","serviceAccount":"default","securityContext":{},"schedulerName":"default-scheduler","tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"priority":0,"enableServiceLinks":true},"status":{}},"oldObject":null,"dryRun":false,"options":{"kind":"CreateOptions","apiVersion":"meta.k8s.io/v1"}}}
{"level":"debug","ts":1608198102.334306,"logger":"mutating_handler","msg":"mutating webhook response","response":{"Patches":[{"op":"add","path":"/spec/containers/1","value":{"env":[{"name":"AWS_REGION","value":"us-east-1"}],"image":"amazon/aws-xray-daemon:latest","name":"xray-daemon","ports":[{"containerPort":0,"name":"xray","protocol":"UDP"}],"resources":{"requests":{"cpu":"10m","memory":"32Mi"}},"securityContext":{"runAsUser":1337}}},{"op":"add","path":"/spec/containers/0/env/1","value":{"name":"ENVOY_ADMIN_ACCESS_LOG_FILE","value":"/tmp/envoy_admin_access.log"}},{"op":"add","path":"/spec/containers/0/env/1","value":{"name":"ENVOY_ADMIN_ACCESS_PORT","value":"9901"}},{"op":"add","path":"/spec/containers/0/env/1","value":{"name":"ENVOY_LOG_LEVEL","value":"info"}},{"op":"add","path":"/spec/containers/0/env/1","value":{"name":"APPMESH_PREVIEW","value":"0"}},{"op":"add","path":"/spec/containers/0/env/1","value":{"name":"APPMESH_VIRTUAL_NODE_NAME","value":"mesh/voting-app/virtualGateway/vote-gw_vote"}},{"op":"add","path":"/spec/containers/0/env/1","value":{"name":"XRAY_DAEMON_PORT","value":"2000"}},{"op":"add","path":"/spec/containers/0/env/1","value":{"name":"AWS_REGION","value":"us-east-1"}},{"op":"replace","path":"/spec/containers/0/env/0/value","value":"1"},{"op":"add","path":"/spec/containers/0/readinessProbe","value":{"exec":{"command":["sh","-c","curl -s http://localhost:9901/server_info | grep state | grep -q LIVE"]},"failureThreshold":3,"initialDelaySeconds":1,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1}}],"uid":"","allowed":true,"patchType":"JSONPatch"}}
{"level":"debug","ts":1608198102.3345273,"logger":"controller-runtime.webhook.webhooks","msg":"wrote response","webhook":"/mutate-v1-pod","UID":"c251863d-2d37-4d2b-90c3-742ce868bc49","allowed":true,"result":{},"resultError":"got runtime.Object without object metadata: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:,Reason:,Details:nil,Code:200,}"}
```

I think the `"containerPort":0` in logs cause the error.

Create a pod which has the label mapping the virtualgate can reproduce the same error.
yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: vote-gw
  namespace: vote
  labels:
    type: gateway
    app: vote-gw
  annotations:
    appmesh.k8s.aws/virtualNode: "vote-v1_vote"
spec:
  containers:
  - name: envoy
    image: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.15.1.0-prod
    ports:
    - containerPort: 8443
    env:
    - name: XRAY_DAEMON_PORT
      value: "2000"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```
**Environment**

* App Mesh controller version
`kubectl get deployment -n appmesh-system appmesh-controller -o json | jq -r ".spec.template.spec.containers[].image" | cut -f2 -d ':'|tail -n1`
`v1.2.0`
* Envoy version
`840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.15.1.0-prod`
* Are you using any integrations? X-ray, Jaeger etc. If so versions?
`amazon/aws-xray-daemon:latest`
* Kubernetes version
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
* Using EKS (yes/no), if so version?
yes, 1.16
**Additional Context**:

**Comment by eph6666** [comment]
I found a temporary solution for others encounter the same problem :
add a annotion to the envoy deploymeny:
```
      annotations:
        appmesh.k8s.aws/sidecarInjectorWebhook: disabled
```
and then,  add detailed configuration of pod Manually:
```
    spec:
      containers:
        - env:
          - name: APPMESH_PREVIEW
            value: "0"
          - name: ENVOY_LOG_LEVEL
            value: info
          - name: ENVOY_ADMIN_ACCESS_PORT
            value: "9901"
          - name: ENVOY_ADMIN_ACCESS_LOG_FILE
            value: /tmp/envoy_admin_access.log
          - name: AWS_REGION
            value: us-east-1
          - name: APPMESH_VIRTUAL_NODE_NAME
            value: mesh/voting-app/virtualGateway/vote-gw_vote
          image: 840364872350.dkr.ecr.us-west-1.amazonaws.com/aws-appmesh-envoy:v1.15.1.0-prod
          imagePullPolicy: IfNotPresent
          name: envoy
          ports:
          - containerPort: 8443
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - curl -s http://localhost:9901/server_info | grep state | grep -q LIVE
```
This pod will not be injected into xray daemon in this way.
