### ISSUE TITLE
VirtualGateway does not have tracing enabled when using jaeger but does with aws xray

### ISSUE THREAD

**Issue by caleygoff-invitae** [aws/aws-app-mesh-controller-for-k8s#460]
**Describe the bug**
We are exploring tracing signals through the mesh and are comparing Jaeger with XRay. I discovered that the VirtualGateway doesn't have `tracing` enabled when using Jaeger on the appmesh-controller and does when using AWS XRay.

**Steps to reproduce**
1) Install Appmesh controller
2) Enable `xray` on the appmesh controller
```
        - --enable-xray-tracing=true
        - --xray-image=amazon/aws-xray-daemon:latest
        - --xray-daemon-port=2000
```
3) Deploy a `VirtualGateway`
4) Exec into the VirtualGateways Envoy container and look at the envoy config file at `/tmp`. Observe the following:
```
staticResources:
  clusters:
  - connectTimeout: 1s
    http2ProtocolOptions: {}
    loadAssignment:
      clusterName: static_cluster_sds_unix_socket
      endpoints:
      - lbEndpoints:
        - endpoint:
            address:
              pipe:
                path: /run/spire/sockets/agent.sock
    name: static_cluster_sds_unix_socket
    type: STATIC
tracing:
  http:
    config:
      daemon_endpoint:
        address: 127.0.0.1
        port_value: 2000
        protocol: UDP
      segment_fields:
        aws:
          app_mesh:
            mesh_name: dev
            virtual_node_name: mesh-ingress-gateway-single-cluster-test_single-cluster-test
        origin: AWS::AppMesh::Proxy
      segment_name: dev/mesh-ingress-gateway-single-cluster-test_single-cluster-test
    name: envoy.tracers.xray
```
5) update  the appmesh controller to use the `jaeger` tracing backend 
```
        - --enable-jaeger-tracing=true
        - --jaeger-address=jaeger-collector.system
        - --jaeger-port=80
```
6) Deploy a `VirtualGateway`
7) Exec into the VirtualGateways `Envoy` container and look at the envoy config file at `/tmp`. Observe the following:
```
staticResources:
  clusters:
  - connectTimeout: 1s
    http2ProtocolOptions: {}
    loadAssignment:
      clusterName: static_cluster_sds_unix_socket
      endpoints:
      - lbEndpoints:
        - endpoint:
            address:
              pipe:
                path: /run/spire/sockets/agent.sock
    name: static_cluster_sds_unix_socket
    type: STATIC
```
**Expected outcome**
I expect there to be a `tracing` attribute on the `VirtualGateway` when using jaeger so we can have tracing at the edge of the mesh similar to xray. As we get the edge tracing there when `xray` is enabled on the appmesh-controller. 

**Environment**

* App Mesh controller version `v1.3.0`
* Envoy version `v1.16.1.0-prod`
* Are you using any integrations? X-ray, Jaeger etc. If so versions? xray `amazon/aws-xray-daemon:latest`; jaeger `otel/opentelemetry-collector-contrib-dev:656611365b896392627736d5d0a1816b1f49bc49`
* Kubernetes version `1.18`
* Using EKS (yes/no), if so version? yes `eks3`

**Additional Context**:

On the `VirtualNode` as expected in the same place on the envoy config we see tracing there like below when using `jaeger` which is missing from the `VirtualGateway` envoy configs.
```
staticResources:
  clusters:
  - connectTimeout: 1s
    loadAssignment:
      clusterName: jaeger
      endpoints:
      - lbEndpoints:
        - endpoint:
            address:
              socketAddress:
                address: jaeger-collector.system
                portValue: 80
    name: jaeger
    type: STRICT_DNS
  - connectTimeout: 1s
    http2ProtocolOptions: {}
    loadAssignment:
      clusterName: static_cluster_sds_unix_socket
      endpoints:
      - lbEndpoints:
        - endpoint:
            address:
              pipe:
                path: /run/spire/sockets/agent.sock
    name: static_cluster_sds_unix_socket
    type: STATIC
tracing:
  http:
    name: envoy.tracers.zipkin
    typedConfig:
      '@type': type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
      collectorCluster: jaeger
      collectorEndpoint: /api/v2/spans
      collectorEndpointVersion: HTTP_JSON
      sharedSpanContext: false
```
