### ISSUE TITLE
Cannot apply both a VirtualGateway and a GatewayRoute in one YAML file after v1.4.0

### ISSUE THREAD

**Issue by fincd-aws** [aws/aws-app-mesh-controller-for-k8s#506]
**Describe the bug**

It appears I am unable to apply both a `VirtualGateway` and a `GatewayRoute` in the same YAML file.

**Steps to reproduce**

1. install working controller v1.4.0 or v1.4.1
2. create a mesh
3. create namespace 'yelb'
4. `kubectl apply -f ingress.yaml` the attached YAML. Output:

```
virtualgateway/ingress-gw created
Error from server (failed to find matching virtualGateway for gatewayRoute: gateway-route-frontend, expecting 1 but found 0): error when creating "ingress.yaml": admission webhook "mgatewayroute.appmesh.k8s.aws" denied the request: failed to find matching virtualGateway for gatewayRoute: gateway-route-frontend, expecting 1 but found 0
```

The dependency of the GatewayRoute on the VirtualGateway seems to get resolved before the VirtualGateway gets made.

Additionally, the controller does NOT log this error message.

**Expected outcome**

The controller should create the objects in the YAML file in order, and notice that a VirtualGateway exists first.

**Environment**

* App Mesh controller version 

v1.4.1
* Envoy version

v1.17.2.0 from controller v1.4.0 recommendations
* Are you using any integrations? X-ray, Jaeger etc. If so versions?

Yes, but they aren't functional nor interfering. Modified https://github.com/aws-containers/eks-app-mesh-polyglot-demo/
* Kubernetes version

v1.21
* Using EKS (yes/no), if so version?

yes, v1.21 eks.1

**Additional Context**:

ingress.yaml
```yaml
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualGateway
metadata:
  name: ingress-gw
  namespace: yelb
spec:
  namespaceSelector:
    matchLabels:
      gateway: ingress-gw
  podSelector:
    matchLabels:
      app: ingress-gw
  listeners:
    - portMapping:
        port: 8088
        protocol: http
  logging:
    accessLog:
      file:
        path: /dev/stdout
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: gateway-route-frontend
  namespace: yelb
spec:
  httpRoute:
    match:
      prefix: "/"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: yelb-ui
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-gw
  namespace: yelb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8088
      name: http
  selector:
    app: ingress-gw

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-gw
  namespace: yelb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-gw
  template:
    metadata:
      labels:
        app: ingress-gw
    spec:
      serviceAccountName: yelb-envoy-proxies
      securityContext:
        fsGroup: 65534
      containers:
        - name: envoy
          image: 840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.17.2.0
          ports:
            - containerPort: 8088
---
```

Controller logs have nothing after the startup, even after applying the yaml:
```log
$ kubectl logs appmesh-controller-7cfbd57dc6-hjnrr -n appmesh-system
{"level":"info","ts":1630451992.0883787,"logger":"setup","msg":"version","GitVersion":"v1.4.1","GitCommit":"50a7999c6de99454152359534fe2536924190836","BuildDate":"2021-08-24T20:28:15+0000"}
{"level":"info","ts":1630451992.088444,"logger":"setup","msg":"Health endpoint","HealthProbeBindAddress":":61779"}
I0831 23:19:53.149030 1 request.go:621] Throttling request took 1.028150992s, request: GET: https://172.20.0.1:443/apis/crd.k8s.amazonaws.com/v1alpha1?timeout=32s
{"level":"info","ts":1630451993.3060653,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8080"}
{"level":"info","ts":1630451996.7746918,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-appmesh-k8s-aws-v1beta2-mesh"}
{"level":"info","ts":1630451996.77565,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-appmesh-k8s-aws-v1beta2-mesh"}
{"level":"info","ts":1630451996.7756639,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-appmesh-k8s-aws-v1beta2-virtualgateway"}
{"level":"info","ts":1630451996.7756743,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-appmesh-k8s-aws-v1beta2-virtualgateway"}
{"level":"info","ts":1630451996.775682,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-appmesh-k8s-aws-v1beta2-gatewayroute"}
{"level":"info","ts":1630451996.7756886,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-appmesh-k8s-aws-v1beta2-gatewayroute"}
{"level":"info","ts":1630451996.7756953,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-appmesh-k8s-aws-v1beta2-virtualnode"}
{"level":"info","ts":1630451996.7757044,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-appmesh-k8s-aws-v1beta2-virtualnode"}
{"level":"info","ts":1630451996.775717,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-appmesh-k8s-aws-v1beta2-virtualservice"}
{"level":"info","ts":1630451996.7757256,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-appmesh-k8s-aws-v1beta2-virtualservice"}
{"level":"info","ts":1630451996.7757342,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-appmesh-k8s-aws-v1beta2-virtualrouter"}
{"level":"info","ts":1630451996.7757432,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-appmesh-k8s-aws-v1beta2-virtualrouter"}
{"level":"info","ts":1630451996.7757502,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}
{"level":"info","ts":1630451996.7757568,"logger":"setup","msg":"adding health check for controller"}
{"level":"info","ts":1630451996.7757716,"logger":"setup","msg":"starting controller"}
I0831 23:19:56.775819 1 leaderelection.go:242] attempting to acquire leader lease appmesh-system/appmesh-controller-leader-election...
{"level":"info","ts":1630451996.776202,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1630451996.8764405,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
{"level":"info","ts":1630451996.8772519,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1630451996.877775,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
{"level":"info","ts":1630451996.877905,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
I0831 23:20:13.644379 1 leaderelection.go:252] successfully acquired lease appmesh-system/appmesh-controller-leader-election
{"level":"info","ts":1630452013.6445243,"logger":"setup","msg":"starting custom controller"}
{"level":"info","ts":1630452013.6449673,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"mesh","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.6456046,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"virtualservice","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.6456468,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"virtualgateway","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.6456826,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"gatewayroute","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.6457162,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"virtualnode","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.6457512,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"virtualrouter","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.645782,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"cloudMap","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.6464787,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"virtualservice","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.64652,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"virtualrouter","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.7470446,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"cloudMap","source":"channel source: 0xc000280730"}
{"level":"info","ts":1630452013.7471364,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"cloudMap"}
{"level":"info","ts":1630452013.7471535,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"cloudMap","worker count":3}
{"level":"info","ts":1630452013.7471874,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"mesh"}
{"level":"info","ts":1630452013.7471952,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"mesh","worker count":1}
{"level":"info","ts":1630452013.7472167,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"virtualservice","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.7472456,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"virtualservice","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.7472672,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"virtualservice"}
{"level":"info","ts":1630452013.747275,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"virtualservice","worker count":3}
{"level":"info","ts":1630452013.7480066,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"virtualrouter","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.7480462,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"virtualrouter"}
{"level":"info","ts":1630452013.7480578,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"virtualrouter","worker count":3}
{"level":"info","ts":1630452013.7483466,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"virtualgateway","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.7483747,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"virtualgateway"}
{"level":"info","ts":1630452013.7483847,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"virtualgateway","worker count":3}
{"level":"info","ts":1630452013.7498043,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"virtualnode","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.7498457,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"virtualnode"}
{"level":"info","ts":1630452013.7498565,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"virtualnode","worker count":3}
{"level":"info","ts":1630452013.7498946,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"gatewayroute","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.7499232,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"gatewayroute","source":"kind source: /, Kind="}
{"level":"info","ts":1630452013.749944,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"gatewayroute"}
{"level":"info","ts":1630452013.7499876,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"gatewayroute","worker count":3}
```
