### ISSUE TITLE
Support x ray sampling rules when injecting envoy proxies

### ISSUE THREAD

**Issue by ollypom** [aws/aws-app-mesh-controller-for-k8s#519]
**Describe the solution you'd like**
In Envoy 1.19.1 you can now configure x-ray sampling rules. 

As per the [docs](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy-config.html)
```
XRAY_SAMPLING_RATE
Specify a sampling rate to override the X-Ray tracer's default sampling
rate of 0.05 (5%). The value should be specified as a decimal between 0 and
1.00 (100%). This will be overridden if XRAY_SAMPLING_RULE_MANIFEST is
specified. This variable is supported with Envoy image version
v1.19.1.0-prod or later.

XRAY_SAMPLING_RULE_MANIFEST
Specify a file path in the Envoy container file system to configure the
localized custom sampling rules for the X-Ray tracer. For more information,
see Sampling rules in the AWS X-Ray Developer Guide. This variable is
supported with Envoy image version v1.19.1.0-prod or later.
```

In my testing an xray sampling file works very well at preventing health check traffic from being sent to xray. However when I define an xray sampling rule in a config map I have to disable auto injection for that deployment and manually mount the config file into the envoy proxy.

```
# Config File
apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-sampling-rules
data:
  sampling-rules.json: |
    {
      "version": 2,
      "rules": [
        {
          "description": "NoHealthChecks",
          "host": "*",
          "http_method": "*",
          "url_path": "/health",
          "fixed_target": 0,
          "rate": 0.0
        }
      ],
      "default": {
        "fixed_target": 1,
        "rate": 0.05
      }
    }

# Deployment
<deployment spec>
        env:
        - name: XRAY_SAMPLING_RULE_MANIFEST
          value: /envoy/sampling-rules.json
<container spec>
        volumeMounts:
        - name: xray-sampling-rules
          mountPath: /envoy/sampling-rules.json
          subPath: sampling-rules.json
          readOnly: true
      volumes:
      - name: xray-sampling-rules
        configMap:
          name: xray-sampling-rules
```

It would be great if you could specify the xray config file when deploying the app mesh controller through an xray install flag. If that flag is passed the sidecar that is injected would have the sampling file configured.

https://github.com/aws/aws-app-mesh-roadmap/issues/95

**Comment by ollypom** [comment]
Just thinking a little bit more about the UX for this feature request. As you may have different sampling rule manifests for different deployments, it maybe more appropriate to use deployment annotations to specify which rule manifest is appropriate for that workload.

**Comment by suniltheta** [comment]
Hi @ollypom thanks for bringing this to our attention. This is a cool option to have, to simplify the usecase. Feel free to propose a PR if you are working towards it.

Also there will be a simpler workaround soon to volume inject the configMap without having to disable the auto inject of envoy sidecar. This change was merged in to this repo recently with this PR https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/488 . So this support is not released yet and should be available on the next version of the aws-app-mesh-controller-for-k8s (v1.5.0 ?).


Here is the changes that I did to the config

```yaml
# Config File
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-sampling-rules
  namespace: ${APP_NAMESPACE}
data:
  sampling-rules.json: |
    {
      "version": 2,
      "rules": [
        {
          "description": "NoHealthChecks",
          "host": "*",
          "http_method": "*",
          "url_path": "/health",
          "fixed_target": 0,
          "rate": 0.0
        }
      ],
      "default": {
        "fixed_target": 1,
        "rate": 0.15
      }
    }
---
# Deployment
<deployment spec>
  template:
    metadata:
      labels:
        app: client
      annotations:
        appmesh.k8s.aws/volumeMounts: xray-sampling-rules:/tmp/xray-sampling-rules/
        appmesh.k8s.aws/sidecarEnv: "XRAY_SAMPLING_RULE_MANIFEST=/tmp/xray-sampling-rules/sampling-rules.json"

<container spec>
      volumes:
      - name: xray-sampling-rules
        configMap:
          name: xray-sampling-rules
---
```

There is a draft PR that you can refer to understand how to do the volumeMount of configMap
https://github.com/aws/aws-app-mesh-examples/pull/453/files
