### ISSUE TITLE
App Liveness- and Readiness- probes failing after sidecar injection is enabled

### ISSUE THREAD

**Issue by RafalMaleska** [aws/aws-app-mesh-controller-for-k8s#526]
**Describe the bug**
after a pod gets a sidecar the kubelet cannot access the pods liveness and redniess probes and the pod fails.

**Steps to reproduce**
put a pod with following probes into a mesh: 

```
livenessProbe:
            httpGet:
              path: /my/app/path/health
              port: 9080
              host: localhost
              scheme: HTTP
            initialDelaySeconds: 8
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /my/app/path/health
              port: 9080
              host: localhost
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
```

**Expected outcome**
pod stays healthy

**Environment**

* App Mesh controller version 1.4.1
* Envoy version v1.19.1.0-prod
* Are you using any integrations? X-ray, Jaeger etc. If so versions? cloudmap / acm-pca 
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? yes

**Additional Context**:
Istio offers a workaround: 
https://istio.io/latest/docs/ops/configuration/mesh/app-health-check/

I'm using: 

```
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - curl -s http://localhost:8080/actuator/health/liveness | sed 's/\(^{"status":"[^"]*"\).*$/\1}/' | grep -q UP
```

which is not possible in containers not including curl
