### ISSUE TITLE
Unable to associate Gateway Route with the Virtual Gateway using only gateway route selector

### ISSUE THREAD

**Issue by dms486** [aws/aws-app-mesh-controller-for-k8s#529]
**Describe the bug**
When creating a Virtual Gateway and Gateway Route, I'm unable to associate the Gateway Route with the Virtual Gateway using a gateway route selector without a namespace selector.

Error from server (failed to find matching virtualGateway for gatewayRoute: vgw-test-route, expecting 1 but found 0): error when creating "vgw-test.yaml": admission webhook "mgatewayroute.appmesh.k8s.aws" denied the request: failed to find matching virtualGateway for gatewayRoute: vgw-test-route, expecting 1 but found 0

**Steps to reproduce**
Create a Virtual Gateway and Gateway Route with a configuration similar to below while only specifying a gatewayRouteSelector.

**Expected outcome**
I expected the Gateway Route to be associated with the Virtual Gateway through the Gateway Route selector label without needing to specify a namespace selector or labeling the namespace.

**Environment**
* App Mesh controller version: v1.4.1
* Envoy version: v1.19.1.0-prod
* Are you using any integrations? X-ray (tag:3.3.3)
* Using EKS (yes/no), if so version? Yes, v1.21.2-eks-0389ca3

**Additional Context**:
```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualGateway
metadata:
  name: vgw-test
  namespace: appmesh-sandbox
spec:
  gatewayRouteSelector:
    matchLabels:
      gateway: vgw-test
  podSelector:
    matchLabels:
      app: vgw-test
  listeners:
    - portMapping:
        port: 8443
        protocol: http
      tls:
        mode: STRICT
        certificate:
          file:
            certificateChain: /certs/test-cert.pem
            privateKey: /certs/test-key.pem
  logging:
    accessLog:
      file:
        path: /dev/stdout
  backendDefaults:
    clientPolicy:
      tls:
        enforce: true
        validation:
          trust:
            file:
              certificateChain: /certs/certs-bundle.pem
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: vgw-test-route
  namespace: appmesh-sandbox
  labels:
    gateway: vgw-test
spec:
  httpRoute:
    match:
      prefix: "/"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: frontend.appmesh-sandbox.svc.cluster.local
```

**Comment by cgchinmay** [comment]
Its meant to be this way, not a bug. You do need a namespace selector. gatewayRouteSelector is to select a subset of gatewayroutes. If you want to search across all namespaces then you can pass an empty namespace selector in addition to the above spec.

**Comment by dms486** [comment]
If I add an empty namespace selector to the above spec, I still see the same error. Do I need to label the namespace too?

**Comment by cgchinmay** [comment]
How is your mesh able to select namespace ? It uses namespace selector. Could you share you spec ?

**Comment by dms486** [comment]
Sure, here is what I have for the mesh

```
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: appmesh-sandbox
spec:
  namespaceSelector:
    matchLabels:
      mesh: appmesh-sandbox
  egressFilter:
    type: ALLOW_ALL
```

**Comment by cgchinmay** [comment]
I think you are hitting a different issue. probably the vgw creation is failing and thats why it cannot find it. I tried following spec and was able to see successful creation
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: howto-k8s-ingress-gateway
  labels:
    mesh: howto-k8s-ingress-gateway
    gateway: ingress-gw
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: howto-k8s-ingress-gateway
spec:
  namespaceSelector:
    matchLabels:
      mesh: howto-k8s-ingress-gateway
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualGateway
metadata:
  name: ingress-gw
  namespace: howto-k8s-ingress-gateway
spec:
  namespaceSelector: {}
  gatewayRouteSelector:
    matchLabels:
      gateway: vgw-test
  podSelector:
    matchLabels:
      app: ingress-gw
  listeners:
    - portMapping:
        port: 8088
        protocol: http
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: gateway-route-headers
  namespace: howto-k8s-ingress-gateway
  labels:
    gateway: vgw-test
spec:
  httpRoute:
    match:
      prefix: "/headers"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: color-headers
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: gateway-route-paths
  namespace: howto-k8s-ingress-gateway
  labels:
    gateway: vgw-test
spec:
  httpRoute:
    match:
      prefix: "/paths"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: color-paths
---
```
1. Check if VGW is actually created, if it has arn associated
2. Check controller logs for any errors

**Comment by cgchinmay** [comment]
@dms486 any updates ?

**Comment by dms486** [comment]
Thanks for looking into it, I ended up having two issues. I wasn't setting the namespaceSelector correctly and I needed to update the virtualServiceRef in the gateway route. After updating it's working now

```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualGateway
metadata:
  name: vgw-test
  namespace: appmesh-sandbox
spec:
  namespaceSelector: {}
  gatewayRouteSelector:
    matchLabels:
      gateway: vgw-test
  podSelector:
    matchLabels:
      app: vgw-test
  listeners:
    - portMapping:
        port: 8443
        protocol: http
      tls:
        mode: STRICT
        certificate:
          file:
            certificateChain: /certs/test-cert.pem
            privateKey: /certs/test-key.pem
  logging:
    accessLog:
      file:
        path: /dev/stdout
  backendDefaults:
    clientPolicy:
      tls:
        enforce: true
        validation:
          trust:
            file:
              certificateChain: /certs/certs-bundle.pem
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: vgw-test-route
  namespace: appmesh-sandbox
  labels:
    gateway: vgw-test
spec:
  httpRoute:
    match:
      prefix: "/"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: frontend
```
