### ISSUE TITLE
Jaeger injector does not work 

### ISSUE THREAD

**Issue by alfianabdi** [aws/aws-app-mesh-controller-for-k8s#551]
**Describe the bug**
From [https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/inject/jaeger.go](url), it says that it should use zipkin HTTP_JSON, but from the actual configuration inside injected envoy, it uses HTTP_PROTO. 

```
tracing:
  http:
    name: envoy.tracers.zipkin
    typedConfig:
      '@type': type.googleapis.com/envoy.config.trace.v3.ZipkinConfig
      collectorCluster: jaeger
      collectorEndpoint: /api/v2/spans
      collectorEndpointVersion: **HTTP_PROTO**
      sharedSpanContext: false
```

**Steps to reproduce**

**Expected outcome**
It should use HTTP_JSON 

**Environment**

* App Mesh controller version: 
v1.4.2
* Envoy version: 
v1.20.0.1-prod
* Are you using any integrations? X-ray, Jaeger etc. If so versions? 
Zipkin V2 receiver via AWS Otel
* Kubernetes version 
1.21
* Using EKS (yes/no), if so version? 
1.21 eks.3

**Additional Context**:
