### ISSUE TITLE
Unable to access instance metadata service

### ISSUE THREAD

**Issue by ollypom** [aws/aws-app-mesh-controller-for-k8s#600]
**Describe the bug**
From my understanding of how AppMesh works you should be able to reach the internal metadata service even if you have the Mesh egress filter turned on.  However in my EKS Cluster I am unable to access the metadata service until I switch the egress filter to `ALLOW_ALL`

This makes me wonder if this env variable set in the init container is working correctly:

```
    - name: APPMESH_EGRESS_IGNORED_IP
      value: 169.254.169.254
```

**Steps to reproduce**

Running:
```
init-image=840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:v5-prod
sidecar-image=840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.22.0.0-prod
controller version 1.5.0
```
Pod is pretty straight forward:

```
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: tester
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: tester
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: tester.default.svc.cluster.local
  logging:
    accessLog:
      file:
        path: "/dev/stdout"
---
apiVersion: v1
kind: Pod
metadata:
  name: sleeper1
  namespace: default
  labels:
    app: tester
  annotations
spec:
  containers:
  - name: sleeper
    image: nicolaka/netshoot:latest
    command: ["sleep", "infinity"]
```

```
$ kubectl exec -it sleeper1 -- /bin/sh
~ # curl http://169.254.169.254/latest/meta-data/placement/availability-zone
curl: (56) Recv failure: Connection reset by peer
```

Flip the Mesh to `ALLOW_ALL`

```
~ # curl http://169.254.169.254/latest/meta-data/placement/availability-zone
eu-west-1b 
```
