### ISSUE TITLE
GatewayRoute Admission Webhook not in keeping with AWS API/UI: match prefix does not need to end in '/'

### ISSUE THREAD

**Issue by conorevans** [aws/aws-app-mesh-controller-for-k8s#712]
**Describe the bug**

With the following YAML

```yaml
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: conor-http
  namespace: mesh
spec:
  httpRoute:
    match:
      prefix: /conor
      port: 9088
    action:
      rewrite:
        hostname:
          defaultTargetHostname: DISABLED
        prefix:
          defaultPrefix: DISABLED
      target:
        virtualService:
          virtualServiceRef:
            name: conor
        port: 64001
```

I get the error

```zsh
✗ k apply -f gatewayroute.yaml
Error from server (Prefix to be matched on must start and end with '/'): error when creating "gatewayroute.yaml": admission webhook "vgatewayroute.appmesh.k8s.aws" denied the request: Prefix to be matched on must start and end with '/'
```

I do not get this in the UI:

![image](https://github.com/aws/aws-app-mesh-controller-for-k8s/assets/43791257/41fd7344-7ecd-498b-9385-a9290076591c)

Nor via the API, where the following Boto3 command:

```python
import boto3

client = boto3.client("appmesh")

response = client.create_gateway_route(
    gatewayRouteName="conor-http",
    meshName="mesh",
    spec={
        "httpRoute": {
            "action": {
                "rewrite": {
                    "hostname": {
                       "defaultTargetHostname": "DISABLED",
                    },
                    "prefix": {
                        "defaultPrefix": "DISABLED",
                    },
                },
                "target": {
                    "port": 64001,
                    "virtualService": {
                        "virtualServiceName": "conor.mesh.svc.cluster.local"
                    },
                },
            },
            "match": {
                "port": 9088,
                "prefix": "/conor",
            },
        },
    },
    virtualGatewayName="<redacted>",
)

print(response)
```

returns

```zsh
✗ python3 gatewayroute.py
{'ResponseMetadata': {'RequestId': '8e75307a-1409-48c5-8269-7e1772ed8bf8', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Wed, 19 Jul 2023 23:23:37 GMT', 'content-type': 'application/json', 'content-length': '893', 'connection': 'keep-alive', 'x-amzn-requestid': '8e75307a-1409-48c5-8269-7e1772ed8bf8'}, 'RetryAttempts': 0}, 'gatewayRoute': {'gatewayRouteName': 'conor-http', 'meshName': 'mesh', 'metadata': {'arn': '<redacted>', 'createdAt': datetime.datetime(2023, 7, 20, 0, 23, 37, 868000, tzinfo=tzlocal()), 'lastUpdatedAt': datetime.datetime(2023, 7, 20, 0, 23, 37, 868000, tzinfo=tzlocal()), 'meshOwner': '<redacted>', 'resourceOwner': '<redacted>', 'uid': '<redacted>', 'version': 1}, 'spec': {'httpRoute': {'action': {'rewrite': {'hostname': {'defaultTargetHostname': 'DISABLED'}, 'prefix': {'defaultPrefix': 'DISABLED'}}, 'target': {'port': 64001, 'virtualService': {'virtualServiceName': 'conor.mesh.svc.cluster.local'}}}, 'match': {'port': 9088, 'prefix': '/conor'}}}, 'status': {'status': 'ACTIVE'}, 'virtualGatewayName': '<redacted>'}}
```

**Steps to reproduce**

I have provided them above.

**Expected outcome**
I do not want the default rewrite behaviour, but I want to match on a prefix. I do _not_ want or expect it to have to end in `/` as trailing slashes are breaking behaviour...

**Environment**

* App Mesh controller version: v1.12.1
* Envoy version: v1.25.4.0-prod
* Are you using any integrations? X-ray, Jaeger etc. If so versions?
* Kubernetes version: 1.25
* Using EKS (yes/no), if so version? yes, 1.25

**Additional Context**: I think it's pretty clear
