### ISSUE TITLE
GrpcRouteMatch port match error despite defining it

### ISSUE THREAD

**Issue by conorevans** [aws/aws-app-mesh-controller-for-k8s#715]
**Describe the bug**

Despite defining `route.grpcRoute.match.port`, I get the reconciler error `BadRequestException: Route must define a port match criteria if the Virtual Router has multiple listeners`

```zsh
✗ kubectl describe virtualrouter conor
Name:         conor
Namespace:    mesh
Labels:       <none>
Annotations:  <none>
API Version:  appmesh.k8s.aws/v1beta2
Kind:         VirtualRouter
Metadata:
  Creation Timestamp:  2023-07-13T14:25:28Z
  Finalizers:
    finalizers.appmesh.k8s.aws/aws-appmesh-resources
  Generation:        10
  Resource Version:  73605192
  UID:               09909b96-03d7-4f7b-a079-72626cf2744f
Spec:
  Aws Name:  conor_mesh
  Listeners:
    Port Mapping:
      Port:      63001
      Protocol:  grpc
    Port Mapping:
      Port:      64001
      Protocol:  http
  Mesh Ref:
    Name:  mesh
    UID:   96d2dcce-b5c5-4b59-8ef8-51bb3eaaf008
  Routes:
    Grpc Route:
      Action:
        Weighted Targets:
          Port:  63001
          Virtual Node Ref:
            Name:  conor
          Weight:  100
      Match:
        Port:          63001
        Service Name:  srv.conor.Conor
    Name:              conor-grpc
    Priority:          2
Status:
  Conditions:
    Last Transition Time:  2023-07-13T14:25:28Z
    Status:                True
    Type:                  VirtualRouterActive
  Observed Generation:     7
  Virtual Router ARN:      arn:aws:appmesh:<redacted>:<redacted>:mesh/mesh/virtualRouter/conor_mesh
Events:
  Type     Reason          Age                From           Message
  ----     ------          ----               ----           -------
  Warning  ReconcileError  6s (x36 over 31m)  VirtualRouter  BadRequestException: Route must define a port match criteria if the Virtual Router has multiple listeners.
```

**Steps to reproduce:**

Define a router similar to

```yaml
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: mesh
  name: conor
spec:
  listeners:
    - portMapping:
        port: 63001
        protocol: grpc
    - portMapping:
        port: 64001
        protocol: http
  routes:
    # - name: conor-http
    #   priority: 1
    #   httpRoute:
    #     action:
    #       weightedTargets:
    #         - virtualNodeRef:
    #             name: conor
    #           weight: 100
    #           port: 64001
    #     match:
    #       prefix: /conor/
    #       port: 64001
    - name: conor-grpc
      priority: 2
      grpcRoute:
        action:
          weightedTargets:
            - virtualNodeRef:
                name: conor
              weight: 100
              port: 63001
        match:
          port: 63001
          serviceName: srv.conor.Conor
```

and try to apply. Note that if you uncomment the HTTP route that one _is_ created correctly.

**Expected outcome**
The gRPC Route configures successfully

**Environment:** EKS 1.26

* App Mesh controller version: v1.25.4.0-prod
* Envoy version
* Are you using any integrations? X-ray, Jaeger etc. If so versions?
* Kubernetes version: v1.26
* Using EKS (yes/no), if so version? v1.26

**Additional Context**:
